name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Cargo Risc Zero installation
      run: |
        git clone https://github.com/justinfrevert/risc0.git
        cd ./risc0
        cargo install --path ./risc0/cargo-risczero --features experimental

    - name: Run tests
      run: cargo risczero test
