name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # - name: Cargo Risc Zero installation
    #   run: |
    #     git clone https://github.com/justinfrevert/risc0.git
    #     cd risc0
    #     cargo run --bin cargo-risczero -- risczero install
    #     cargo install --path ./risc0/cargo-risczero --features experimental

    - name: Install Cargo Risc Zero tool
      uses: taiki-e/cache-cargo-install-action@v1
      with:
        tool: cargo-risczero
        git: https://github.com/justinfrevert/risc0.git
        rev: 6c2040cfcc179ddc961e5cf2bc793b7b2518e203
        # Add other options like `tag`, `rev`, etc. if needed

    - name: Run tests
      run: cargo risczero test

    - name: Move Proofs
      run: |
        mkdir -p ./proofs
        find ./target/riscv32im-risc0-zkvm-elf/debug/deps -name '*_proof.json' -exec mv {} ./node_client/proofs \;

    - name: Send to blockchain node
      run: |
        cd node_client
        cargo run